name: Build the documentation

on:
  workflow_dispatch:

  push:

  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-gallery

      - name: Install PyJuice
        run: |
          pip install -e .

      - name: Build the documentation with Sphinx
        run: |
          sphinx-build -b html docs/source docs/build/html

      - name: Publish the documentation
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          CLEAN: true